-- Separate owner inventory tables.
-- This does NOT delete or modify existing devices/monitors data.

CREATE TABLE IF NOT EXISTS `iman_hustle_items` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `item_type` ENUM('Device','Monitor') NOT NULL DEFAULT 'Device',
    `asset_id` VARCHAR(100) NULL,
    `manufacturer` VARCHAR(100) NULL,
    `model_name` VARCHAR(190) NULL,
    `form_factor` VARCHAR(100) NULL,
    `processor` VARCHAR(190) NULL,
    `ram` VARCHAR(50) NULL,
    `storage` VARCHAR(100) NULL,
    `serial_number` VARCHAR(190) NULL,
    `grade` VARCHAR(50) NULL,
    `buying_price` DECIMAL(12,2) NULL,
    `planned_selling_price` DECIMAL(12,2) NULL,
    `notes` TEXT NULL,
    `location` ENUM('KIMATHI','MOI','WAREHOUSE') NULL,
    `status` ENUM('In Stock','Sold') NOT NULL DEFAULT 'In Stock',
    `sales_person` VARCHAR(190) NULL,
    `selling_price` DECIMAL(12,2) NULL,
    `payment_status` ENUM('paid','unpaid') NULL,
    `sold_at` DATETIME NULL,
    `added_by` INT NULL,
    `date_added` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_iman_hustle_serial` (`serial_number`),
    KEY `idx_iman_hustle_status` (`status`),
    KEY `idx_iman_hustle_location` (`location`),
    KEY `idx_iman_hustle_date_added` (`date_added`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `iman_inventory_items` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `item_type` ENUM('Device','Monitor') NOT NULL DEFAULT 'Device',
    `asset_id` VARCHAR(100) NULL,
    `buying_usd` DECIMAL(12,2) NULL,
    `selling_usd` DECIMAL(12,2) NULL,
    `buying_price` DECIMAL(12,2) NULL,
    `planned_selling_price` DECIMAL(12,2) NULL,
    `manufacturer` VARCHAR(100) NULL,
    `model_name` VARCHAR(190) NULL,
    `processor` VARCHAR(190) NULL,
    `ram` VARCHAR(50) NULL,
    `storage` VARCHAR(100) NULL,
    `serial_number` VARCHAR(190) NULL,
    `grade` VARCHAR(50) NULL,
    `touch_screen` VARCHAR(50) NULL,
    `webcam` VARCHAR(100) NULL,
    `notes` TEXT NULL,
    `location` ENUM('KIMATHI','MOI','WAREHOUSE') NULL,
    `status` ENUM('In Stock','Sold') NOT NULL DEFAULT 'In Stock',
    `sales_person` VARCHAR(190) NULL,
    `selling_price` DECIMAL(12,2) NULL,
    `payment_status` ENUM('paid','unpaid') NULL,
    `sold_at` DATETIME NULL,
    `added_by` INT NULL,
    `date_added` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_iman_inventory_serial` (`serial_number`),
    KEY `idx_iman_inventory_status` (`status`),
    KEY `idx_iman_inventory_location` (`location`),
    KEY `idx_iman_inventory_date_added` (`date_added`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
