<?php
session_start();
require_once __DIR__.'/../config/db.php';
require_once __DIR__.'/../includes/auth_check.php';
require_once __DIR__.'/../includes/owner_inventory_access.php';
$access=requireOwnerInventoryAccess($conn);$user_id=(int)$access['user_id'];$userBranch=$access['branch']?:null;
require_once __DIR__.'/../vendor/autoload.php';
use PhpOffice\PhpSpreadsheet\IOFactory;use PhpOffice\PhpSpreadsheet\Spreadsheet;use PhpOffice\PhpSpreadsheet\Writer\Xlsx;use PhpOffice\PhpSpreadsheet\Cell\Coordinate;use PhpOffice\PhpSpreadsheet\Style\Fill;use PhpOffice\PhpSpreadsheet\Style\Border;
$error='';$success='';$duplicates=[];
function val($r,$i){$v=trim((string)($r[$i]??''));return($v===''||$v==='-')?null:$v;}
function numv($v){$v=trim((string)$v);if($v===''||$v==='-')return null;$v=str_ireplace(['KES','KSH','USD'],'',$v);$v=str_replace([',','$'],'',$v);return is_numeric(trim($v))?(float)trim($v):null;}
function statv($v){$v=strtolower(trim((string)$v));if($v===''||$v==='-')return'In Stock';if($v==='sold')return'Sold';return in_array($v,['in stock','instock','in-stock'],true)?'In Stock':'In Stock';}
function locv($v){$v=strtoupper(trim((string)$v));return in_array($v,['KIMATHI','MOI','WAREHOUSE'],true)?$v:null;}
function inferType($form,$cpu,$ram,$storage){$f=strtolower(trim((string)$form));if(str_contains($f,'monitor')||str_contains($f,'display'))return'Monitor';return(trim((string)$cpu)===''&&trim((string)$ram)===''&&trim((string)$storage)==='')?'Monitor':'Device';}
$headers=['Asset ID', 'MFG', 'Model', 'Form Factor', 'CPU', 'Ram', 'Storage', 'Serial', 'Grade', 'B.P', 'S.P', 'PROFIT', 'NOTES', 'Status'];$sample=['IH-001', 'HP', 'EliteBook 840 G8', 'Laptop', 'Core i5 11th Gen', '16GB', '512GB SSD', 'SN001', 'A', '25000', '35000', '10000', '', 'In Stock'];
if(isset($_GET['template'])){$b=new Spreadsheet();$s=$b->getActiveSheet();foreach($headers as$i=>$h){$c=Coordinate::stringFromColumnIndex($i+1);$s->setCellValue($c.'1',$h);$s->setCellValue($c.'2',$sample[$i]??'');$s->getColumnDimension($c)->setAutoSize(true);}$last=Coordinate::stringFromColumnIndex(count($headers));$s->getStyle('A1:'.$last.'1')->getFont()->setBold(true);$s->getStyle('A1:'.$last.'1')->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFD7B729');$s->freezePane('A2');while(ob_get_level())ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="imans_hustle_upload_template.xlsx"');(new Xlsx($b))->save('php://output');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_FILES['excel_file'])){try{$book=IOFactory::load($_FILES['excel_file']['tmp_name']);$rows=$book->getActiveSheet()->toArray(null,true,true,false);if(!$rows)throw new Exception('Spreadsheet is empty.');array_shift($rows);$check=$conn->prepare("SELECT id FROM iman_hustle_items WHERE serial_number=? LIMIT 1");$insert=$conn->prepare("INSERT INTO iman_hustle_items(item_type,asset_id,manufacturer,model_name,form_factor,processor,ram,storage,serial_number,grade,buying_price,planned_selling_price,notes,location,status,selling_price,sold_at,added_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");$count=0;foreach($rows as$i=>$r){if(!array_filter($r,fn($v)=>trim((string)$v)!==''))continue;
            $asset=val($r,0);$mfg=val($r,1);$model=val($r,2);$form=val($r,3);$cpu=val($r,4);$ram=val($r,5);$storage=val($r,6);$serial=val($r,7);$grade=val($r,8);
            $bp=numv($r[9]??null);$sp=numv($r[10]??null);$notes=val($r,12);$status=statv($r[13]??null);
            $itemType=inferType($form,$cpu,$ram,$storage);
            $location=$userBranch!==''?$userBranch:null;
            if($serial!==null){$check->execute([$serial]);if($check->fetchColumn()){$duplicates[]=$serial;continue;}}
            $actual=$status==='Sold'?$sp:null;$soldAt=$status==='Sold'?date('Y-m-d H:i:s'):null;
            $insert->execute([$itemType,$asset,$mfg,$model,$form,$cpu,$ram,$storage,$serial,$grade,$bp,$sp,$notes,$location,$status,$actual,$soldAt,$user_id]);
        $count++;}$success="$count row(s) uploaded successfully.";}catch(Throwable$e){$error=$e->getMessage();}}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Iman's Hustle Bulk Upload</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"><style>
:root{--p:#1a4b2a;--pl:#2a6b3a;--bg:#f3f4f6;--b:#e5e7eb;--m:#6b7280;--gold:#d7b729}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui;background:var(--bg);color:#1f2937}.main{margin-left:260px;padding:2rem}.head,.box{background:#fff;border:1px solid var(--b);border-radius:14px;padding:1.4rem;margin-bottom:1rem;box-shadow:0 1px 2px #0000000d}.breadcrumb{color:var(--m);font-size:.86rem}.breadcrumb a{color:var(--p);text-decoration:none}.actions{display:flex;gap:.6rem;flex-wrap:wrap;margin-top:1rem}.btn{background:var(--p);color:#fff;padding:.7rem .9rem;border:0;border-radius:8px;text-decoration:none;font-weight:650;cursor:pointer;display:inline-flex;gap:.4rem;align-items:center}.btn.secondary{background:#6b7280}.alert{padding:1rem;border-radius:9px;margin-bottom:1rem}.ok{background:#ecfdf5;color:#065f46}.err{background:#fef2f2;color:#991b1b}.warn{background:#fffbeb;color:#92400e}.format{overflow:auto;border:1px solid var(--b);border-radius:9px;margin:1rem 0}table{border-collapse:collapse;min-width:1100px;width:100%}th,td{padding:.65rem;border-right:1px solid var(--b);border-bottom:1px solid var(--b);white-space:nowrap;font-size:.78rem}th{background:var(--gold)}.rules{color:var(--m);font-size:.86rem;line-height:1.65}input[type=file]{width:100%;padding:.8rem;border:1px solid #d1d5db;border-radius:8px;background:#fff}@media(max-width:1200px){.main{margin-left:0;padding:5rem 1rem 1rem}}
</style></head><body><?php include __DIR__.'/../includes/sidebar.php';?><main class="main">
<section class="head"><h1 style="margin-top:0"><i class="fas fa-file-excel"></i> Iman's Hustle Bulk Upload</h1><div class="breadcrumb"><a href="../dashboard/superadmindashboard.php"><i class="fas fa-home"></i> Dashboard</a> / <a href="overview.php">Iman's Hustle</a> / Bulk Upload</div><p class="rules">This uploader writes only to <strong>iman_hustle_items</strong>. It does not create or modify normal Devices/Monitors records.</p><div class="actions"><a class="btn" href="?template=1"><i class="fas fa-download"></i> Download .xlsx Template</a><a class="btn secondary" href="add_device.php"><i class="fas fa-plus"></i> Add Single Item</a><a class="btn secondary" href="overview.php">Back to Overview</a></div></section>
<?php if($success):?><div class="alert ok"><?=htmlspecialchars($success)?></div><?php endif;?><?php if($error):?><div class="alert err"><?=htmlspecialchars($error)?></div><?php endif;?><?php if($duplicates):?><div class="alert warn"><strong>Duplicate serials skipped:</strong> <?=htmlspecialchars(implode(', ',array_unique($duplicates)))?></div><?php endif;?>
<section class="box"><h2>Required Excel Layout</h2><p class="rules">Keep the columns in this order. The header row should remain present. Individual cells may be empty.</p><div class="format"><table><thead><tr><?php foreach($headers as$h):?><th><?=htmlspecialchars($h)?></th><?php endforeach;?></tr></thead><tbody><tr><?php foreach($sample as$v):?><td><?=htmlspecialchars((string)$v)?></td><?php endforeach;?></tr></tbody></table></div><ul class="rules">
        <li><strong>All cells are optional.</strong> Empty cells are stored as NULL; they do not reject the row.</li>
        <li><strong>Status:</strong> blank or "-" automatically becomes In Stock. Use Sold only for already-sold stock.</li>
        <li><strong>Item Type:</strong> inferred automatically. Monitor-like rows can live in this independent table too.</li>
        <li><strong>B.P / S.P:</strong> numeric values; commas and KES/KSH are accepted. PROFIT does not need to be supplied because reports calculate it.</li>
        <li><strong>Location:</strong> this existing Hustle sheet has no LOCATION column, so the uploader uses the logged-in user's assigned branch when available.</li>
        </ul></section>
<section class="box"><h2>Upload File</h2><form method="post" enctype="multipart/form-data"><input type="file" name="excel_file" accept=".xlsx,.xls,.csv" required><button class="btn" style="margin-top:1rem"><i class="fas fa-upload"></i> Upload and Process</button></form></section>
</main><?php require_once __DIR__.'/../includes/footer.php';?></body></html>