<?php
if (!isset($ownerKey,$ownerLabel,$reportMode)) die('Inventory report configuration missing.');
session_start();
require_once __DIR__.'/../config/db.php';
require_once __DIR__.'/auth_check.php';
$role=$_SESSION['role']; $user_id=(int)$_SESSION['user_id'];
if(!in_array($role,['super_admin','inventory_admin','manager'],true)) die('ACCESS DENIED.');
$user_branch=''; if($role==='manager'){ $q=$conn->prepare('SELECT branch FROM users WHERE id=?');$q->execute([$user_id]);$user_branch=(string)($q->fetchColumn()?:''); }
$serial=trim($_GET['serial']??'');$model=trim($_GET['model']??'');$branch=trim($_GET['branch']??'');$category=trim($_GET['category']??'');$status=trim($_GET['status']??'');
$date_from=trim($_GET['date_from']??'');$date_to=trim($_GET['date_to']??'');
if($reportMode==='overview'){ if($date_from==='')$date_from=date('Y-m-01'); if($date_to==='')$date_to=date('Y-m-d'); }
$sql="SELECT d.*,c.category_name,ua.full_name added_by_name,us.full_name sold_by_name FROM devices d LEFT JOIN categories c ON c.id=d.category_id LEFT JOIN users ua ON ua.id=d.added_by LEFT JOIN users us ON us.id=d.sold_by WHERE d.inventory_owner=:owner";
$params=['owner'=>$ownerKey];
if($reportMode==='instock')$sql.=" AND d.status='In Stock'"; elseif($reportMode==='sold')$sql.=" AND d.status='Sold'"; elseif($status!==''){$sql.=' AND d.status=:status';$params['status']=$status;}
if($role==='manager'&&$user_branch!==''){$sql.=' AND d.branch=:mb';$params['mb']=$user_branch;} elseif($branch!==''){$sql.=' AND d.branch=:branch';$params['branch']=$branch;}
if($serial!==''){$sql.=' AND d.serial_number LIKE :serial';$params['serial']="%$serial%";} if($model!==''){$sql.=' AND d.model_name LIKE :model';$params['model']="%$model%";} if($category!==''){$sql.=' AND d.category_id=:cat';$params['cat']=(int)$category;}
if($reportMode==='overview'){if($date_from!==''){$sql.=' AND DATE(d.date_added)>=:df';$params['df']=$date_from;}if($date_to!==''){$sql.=' AND DATE(d.date_added)<=:dt';$params['dt']=$date_to;}}
if($reportMode==='sold'){if($date_from!==''){$sql.=' AND DATE(d.sold_at)>=:df';$params['df']=$date_from;}if($date_to!==''){$sql.=' AND DATE(d.sold_at)<=:dt';$params['dt']=$date_to;}}
$sql.=$reportMode==='sold'?' ORDER BY d.sold_at DESC':' ORDER BY d.date_added DESC'; $stmt=$conn->prepare($sql);$stmt->execute($params);$devices=$stmt->fetchAll(PDO::FETCH_ASSOC);
$cats=$conn->query('SELECT id,category_name FROM categories ORDER BY category_name')->fetchAll(PDO::FETCH_ASSOC);
$maintenance=[];if($reportMode==='overview'&&$devices){$sns=array_column($devices,'serial_number');$ph=implode(',',array_fill(0,count($sns),'?'));$m=$conn->prepare("SELECT m.*,u.full_name performed_by_name FROM maintenance m LEFT JOIN users u ON u.id=m.performed_by WHERE m.device_serial IN ($ph) ORDER BY m.date_performed ASC");$m->execute($sns);foreach($m->fetchAll(PDO::FETCH_ASSOC) as $r)$maintenance[$r['device_serial']][]=$r;}
function ownerMaint($rows){if(!$rows)return 'No maintenance records';$out=[];foreach($rows as $r){$c=[];if($r['old_ram']!==null||$r['new_ram']!==null)$c[]='RAM: '.($r['old_ram']??'?').'GB → '.($r['new_ram']??'?').'GB';if($r['old_storage']!==null||$r['new_storage']!==null)$c[]='Storage: '.($r['old_storage']??'?').'GB → '.($r['new_storage']??'?').'GB';if(($r['old_graphics']??'')!==''||($r['new_graphics']??'')!=='')$c[]='Graphics: '.($r['old_graphics']?:'?').' → '.($r['new_graphics']?:'?');if(!empty($r['notes']))$c[]='Notes: '.$r['notes'];$out[]=date('d M Y H:i',strtotime($r['date_performed'])).' — '.implode('; ',$c).' — '.($r['performed_by_name']??'Unknown');}return implode("\n",$out);}
function ownerStorage($d){return !empty($d['storage_capacity'])?$d['storage_capacity'].'GB '.($d['storage_type']??''):'';}
function moneyCell($v){return $v===null||$v===''?'-':'KES '.number_format((float)$v,2);}
function dashCell($v){$v=trim((string)($v??''));return $v===''?'-':$v;}
function dollarCell($v){if($v===null||trim((string)$v)==='')return '-';$raw=str_replace([',','$'],'',trim((string)$v));return is_numeric($raw)?'$'.number_format((float)$raw,2):'$'.trim((string)$v);}
function ownerManufacturer($d){$model=strtoupper(trim((string)($d['model_name']??'')));if(preg_match('/\bHP\b|HEWLETT[ -]?PACKARD/',$model))return 'HP';if(preg_match('/\bDELL\b/',$model))return 'Dell';if(preg_match('/\bLENOVO\b|THINKPAD|THINKCENTRE|IDEAPAD/',$model))return 'Lenovo';if(preg_match('/\bTOSHIBA\b|DYNABOOK/',$model))return 'Toshiba';if(preg_match('/\bAPPLE\b|MACBOOK|IMAC/',$model))return 'Apple';if(preg_match('/\bASUS\b/',$model))return 'ASUS';if(preg_match('/\bACER\b/',$model))return 'Acer';return dashCell($d['manufacturer']??'');}
function actualProfit($d){if(($d['selling_price']??null)===null||($d['selling_price']??'')===''||($d['buying_price']??null)===null||($d['buying_price']??'')==='')return null;return (float)$d['selling_price']-(float)$d['buying_price'];}
function imanSp($d){return ($d['selling_price']??null)!==null&&($d['selling_price']??'')!==''?$d['selling_price']:($d['price']??null);}
$total=count($devices);$inStock=count(array_filter($devices,fn($d)=>$d['status']==='In Stock'));$sold=count(array_filter($devices,fn($d)=>$d['status']==='Sold'));$revenue=array_sum(array_map(fn($d)=>(float)($d['selling_price']??0),$devices));$pageTitle=$reportMode==='overview'?'Overview':($reportMode==='instock'?'In Stock':'Sold');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title><?=htmlspecialchars($ownerLabel.' '.$pageTitle)?> | Mombasa Computers</title><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"><style>
:root{--p:#1a4b2a;--bg:#f3f4f6;--b:#e5e7eb;--t:#1f2937;--m:#6b7280}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:var(--bg);color:var(--t)}.main{margin-left:260px;padding:2rem;min-height:100vh}.head,.filters,.card,.tablebox{background:#fff;border:1px solid var(--b);border-radius:14px;box-shadow:0 1px 2px #0000000d}.head{padding:1.4rem 1.6rem;margin-bottom:1rem}.head h1{margin:0 0 .35rem;font-size:1.65rem}.tabs{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:1rem}.tabs a{padding:.55rem .9rem;border-radius:8px;text-decoration:none;color:var(--p);border:1px solid var(--b);font-weight:600}.tabs a.active{background:var(--p);color:#fff}.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:1rem;margin:1rem 0}.card{padding:1rem}.n{font-size:1.55rem;font-weight:800;color:var(--p)}.l{font-size:.78rem;color:var(--m)}.filters{padding:1rem;margin-bottom:1rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:.75rem}.g{display:flex;flex-direction:column;gap:.3rem}.g label{font-size:.78rem;color:var(--m);font-weight:600}.g input,.g select{padding:.62rem;border:1px solid #d1d5db;border-radius:8px}.filter-actions{display:flex;gap:.5rem;align-items:end;flex-wrap:wrap}.btn{padding:.58rem .78rem;border:0;border-radius:8px;background:var(--p);color:#fff;text-decoration:none;cursor:pointer;display:inline-flex;align-items:center;gap:.35rem;white-space:nowrap;font-weight:650}.secondary{background:#6b7280}.excel{background:#217346}.tablebox{overflow:hidden}.scroll{overflow:auto}table{border-collapse:separate;border-spacing:0;width:100%;min-width:1750px;font-size:.79rem}th,td{padding:.72rem .78rem;border-bottom:1px solid #edf0f2;text-align:left;vertical-align:middle;white-space:nowrap}th{position:sticky;top:0;z-index:2;background:#d7b729;color:#171717;font-weight:800;letter-spacing:.015em;border-bottom:2px solid #b99d1e}tbody tr:nth-child(even){background:#fafbfc}tbody tr:hover{background:#f5f8f6}.sn{font-family:monospace;font-weight:700}.badge{display:inline-block;padding:.22rem .52rem;background:#dcfce7;color:#166534;border-radius:999px;font-size:.72rem;font-weight:750}.badge.sold{background:#fee2e2;color:#b91c1c}.maint{white-space:pre-line!important;min-width:320px;max-width:420px;line-height:1.45}.notes{white-space:normal!important;min-width:180px;max-width:260px}.action-cell{min-width:105px;text-align:center}.num{text-align:center;color:#6b7280;font-weight:700}.money{font-variant-numeric:tabular-nums;font-weight:650}.profit-positive{color:#047857}.profit-negative{color:#b91c1c}.empty{padding:3rem;text-align:center;color:var(--m)}@media(max-width:1200px){.main{margin-left:0;padding:5rem 1rem 1rem}}
</style></head><body><?php include __DIR__.'/sidebar.php';?><main class="main"><section class="head"><h1><i class="fas fa-boxes-stacked"></i> <?=htmlspecialchars($ownerLabel)?> — <?=htmlspecialchars($pageTitle)?></h1><div style="color:var(--m)">Owner-specific inventory layout.</div><div class="tabs"><a class="<?=$reportMode==='overview'?'active':''?>" href="overview.php">Overview</a><a class="<?=$reportMode==='instock'?'active':''?>" href="instock.php">In Stock</a><a class="<?=$reportMode==='sold'?'active':''?>" href="sold.php">Sold</a></div></section>
<section class="stats"><div class="card"><div class="n"><?=$total?></div><div class="l"><?= $reportMode==='overview'?'TOTAL DEVICES':'MATCHING DEVICES' ?></div></div><?php if($reportMode==='overview'):?><div class="card"><div class="n"><?=$inStock?></div><div class="l">IN STOCK</div></div><div class="card"><div class="n"><?=$sold?></div><div class="l">SOLD</div></div><?php endif;?><?php if($reportMode==='sold'):?><div class="card"><div class="n">KES <?=number_format($revenue,2)?></div><div class="l">ACTUAL SALES VALUE</div></div><?php endif;?></section>
<section class="filters"><form class="grid" method="get"><div class="g"><label>Serial</label><input name="serial" value="<?=htmlspecialchars($serial)?>"></div><div class="g"><label>Model</label><input name="model" value="<?=htmlspecialchars($model)?>"></div><div class="g"><label>Category</label><select name="category"><option value="">All</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>" <?=$category==(string)$c['id']?'selected':''?>><?=htmlspecialchars($c['category_name'])?></option><?php endforeach;?></select></div><?php if($role!=='manager'):?><div class="g"><label>Branch</label><select name="branch"><option value="">All</option><option <?=$branch==='KIMATHI'?'selected':''?>>KIMATHI</option><option <?=$branch==='MOI'?'selected':''?>>MOI</option><option <?=$branch==='WAREHOUSE'?'selected':''?>>WAREHOUSE</option></select></div><?php endif;?><?php if($reportMode==='overview'):?><div class="g"><label>Status</label><select name="status"><option value="">All</option><?php foreach(['In Stock','Sold','Faulty','Under Repair','Disposed'] as $st):?><option <?=$status===$st?'selected':''?>><?=$st?></option><?php endforeach;?></select></div><?php endif;?><?php if($reportMode==='overview'||$reportMode==='sold'):?><div class="g"><label><?=$reportMode==='sold'?'Sold From':'Added From'?></label><input type="date" name="date_from" value="<?=htmlspecialchars($date_from)?>"></div><div class="g"><label><?=$reportMode==='sold'?'Sold To':'Added To'?></label><input type="date" name="date_to" value="<?=htmlspecialchars($date_to)?>"></div><?php endif;?><div class="filter-actions"><button class="btn"><i class="fas fa-search"></i> Filter</button><a class="btn secondary" href="<?=$reportMode?>.php">Reset</a><a class="btn excel" href="export_excel.php?<?=htmlspecialchars(http_build_query(array_merge($_GET,['report'=>$reportMode])))?>"><i class="fas fa-file-excel"></i> Export Excel</a></div></form></section>
<section class="tablebox"><div class="scroll"><?php if(!$devices):?><div class="empty">No records found.</div><?php else:?><table><thead><tr>
<?php if($ownerKey==='imans_hustle'):?><?php foreach(['Asset ID','MFG','Model','Form Factor','CPU','RAM','HDD','Serial','Grade','B.P','S.P','PROFIT','NOTES'] as $h):?><th><?=$h?></th><?php endforeach;?><?php else:?><th>#</th><?php foreach(['Asset ID','Buying $','Selling $','BP','SP','PROFIT','MFG','Model','CPU','RAM','HDD','Serial #','Grade','Touch Screen','Webcam','Notes','LOCATION'] as $h):?><th><?=$h?></th><?php endforeach;?><?php endif;?><th>Status</th><?php if($reportMode==='overview'):?><th>Maintenance / Changes</th><?php endif;?><?php if($reportMode==='sold'):?><th>Sold By</th><th>Sold At</th><th>Actual Selling Price</th><?php endif;?><th>Action</th></tr></thead><tbody>
<?php foreach($devices as $rowIndex=>$d):?><tr>
<?php if($ownerKey==='imans_hustle'):?><td><?=htmlspecialchars($d['asset_id']??'')?></td><td><?=htmlspecialchars($d['manufacturer']??'')?></td><td><strong><?=htmlspecialchars($d['model_name']??'')?></strong></td><td><?=htmlspecialchars($d['form_factor']??'')?></td><td><?=htmlspecialchars($d['processor']??'')?></td><td><?=htmlspecialchars($d['ram']??'')?></td><td><?=htmlspecialchars(ownerStorage($d))?></td><td class="sn"><?=htmlspecialchars($d['serial_number'])?></td><td><?=htmlspecialchars($d['grade']??'')?></td><td><?=moneyCell($d['buying_price']??null)?></td><td><?=moneyCell($d['price']??null)?></td><td><?=moneyCell($d['owner_profit']??null)?></td><td class="notes"><?=htmlspecialchars($d['owner_notes']??'')?></td>
<?php else:?><?php $profit=actualProfit($d);?><td class="num"><?=($rowIndex+1)?></td><td><?=htmlspecialchars(dashCell($d['asset_id']??''))?></td><td class="money"><?=htmlspecialchars(dollarCell($d['symetic']??null))?></td><td class="money"><?=htmlspecialchars(dollarCell($d['dollar_value']??null))?></td><td class="money"><?=moneyCell($d['buying_price']??null)?></td><td class="money"><?=moneyCell(imanSp($d))?></td><td class="money <?=$profit!==null&&$profit<0?'profit-negative':'profit-positive'?>"><?=moneyCell($profit)?></td><td><?=htmlspecialchars(ownerManufacturer($d))?></td><td><strong><?=htmlspecialchars(dashCell($d['model_name']??''))?></strong></td><td><?=htmlspecialchars(dashCell($d['processor']??''))?></td><td><?=!empty($d['ram'])?htmlspecialchars((string)$d['ram']).' GB':'-'?></td><td><?=htmlspecialchars(ownerStorage($d)?:'-')?></td><td class="sn"><?=htmlspecialchars(dashCell($d['serial_number']??''))?></td><td><?=htmlspecialchars(dashCell($d['grade']??''))?></td><td><?=htmlspecialchars(dashCell($d['touch']??''))?></td><td><?=htmlspecialchars(dashCell($d['webcam']??''))?></td><td class="notes"><?=htmlspecialchars(dashCell($d['owner_notes']??''))?></td><td><?=htmlspecialchars(dashCell($d['owner_location']??($d['branch']??'')))?></td><?php endif;?>
<td><span class="badge <?=$d['status']==='Sold'?'sold':''?>"><?=htmlspecialchars($d['status'])?></span></td><?php if($reportMode==='overview'):?><td class="maint"><?=htmlspecialchars(ownerMaint($maintenance[$d['serial_number']]??[]))?></td><?php endif;?><?php if($reportMode==='sold'):?><td><?=htmlspecialchars($d['sold_by_name']??'Unknown')?></td><td><?=$d['sold_at']?date('d M Y H:i',strtotime($d['sold_at'])):'—'?></td><td><?=moneyCell($d['selling_price']??null)?></td><?php endif;?><td class="action-cell"><a class="btn" href="../devices/view_device.php?sn=<?=urlencode($d['serial_number'])?>"><i class="fas fa-eye"></i> View</a></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></section></main></body></html>
