<?php
ob_start();
if (!isset($ownerKey,$ownerLabel)) die('Inventory export configuration missing.');
session_start();
require_once __DIR__.'/../config/db.php';
require_once __DIR__.'/auth_check.php';
require_once __DIR__.'/../vendor/autoload.php';
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
$role=$_SESSION['role'];$uid=(int)$_SESSION['user_id'];if(!in_array($role,['super_admin','inventory_admin','manager'],true))die('ACCESS DENIED.');
$mode=trim($_GET['report']??'overview');if(!in_array($mode,['overview','instock','sold'],true))$mode='overview';
$user_branch='';if($role==='manager'){$q=$conn->prepare('SELECT branch FROM users WHERE id=?');$q->execute([$uid]);$user_branch=(string)($q->fetchColumn()?:'');}
$serial=trim($_GET['serial']??'');$model=trim($_GET['model']??'');$branch=trim($_GET['branch']??'');$category=trim($_GET['category']??'');$status=trim($_GET['status']??'');$df=trim($_GET['date_from']??'');$dt=trim($_GET['date_to']??'');
if($mode==='overview'){if($df==='')$df=date('Y-m-01');if($dt==='')$dt=date('Y-m-d');}
$sql="SELECT d.*,c.category_name,us.full_name sold_by_name FROM devices d LEFT JOIN categories c ON c.id=d.category_id LEFT JOIN users us ON us.id=d.sold_by WHERE d.inventory_owner=:owner";$p=['owner'=>$ownerKey];
if($mode==='instock')$sql.=" AND d.status='In Stock'";elseif($mode==='sold')$sql.=" AND d.status='Sold'";elseif($status!==''){$sql.=' AND d.status=:status';$p['status']=$status;}
if($role==='manager'&&$user_branch!==''){$sql.=' AND d.branch=:mb';$p['mb']=$user_branch;}elseif($branch!==''){$sql.=' AND d.branch=:br';$p['br']=$branch;}
if($serial!==''){$sql.=' AND d.serial_number LIKE :sn';$p['sn']="%$serial%";}if($model!==''){$sql.=' AND d.model_name LIKE :model';$p['model']="%$model%";}if($category!==''){$sql.=' AND d.category_id=:cat';$p['cat']=(int)$category;}
if($mode==='overview'){if($df!==''){$sql.=' AND DATE(d.date_added)>=:df';$p['df']=$df;}if($dt!==''){$sql.=' AND DATE(d.date_added)<=:dt';$p['dt']=$dt;}}
if($mode==='sold'){if($df!==''){$sql.=' AND DATE(d.sold_at)>=:df';$p['df']=$df;}if($dt!==''){$sql.=' AND DATE(d.sold_at)<=:dt';$p['dt']=$dt;}}
$sql.=$mode==='sold'?' ORDER BY d.sold_at DESC':' ORDER BY d.date_added DESC';$st=$conn->prepare($sql);$st->execute($p);$devices=$st->fetchAll(PDO::FETCH_ASSOC);
$maint=[];if($mode==='overview'&&$devices){$sns=array_column($devices,'serial_number');$ph=implode(',',array_fill(0,count($sns),'?'));$m=$conn->prepare("SELECT m.*,u.full_name performed_by_name FROM maintenance m LEFT JOIN users u ON u.id=m.performed_by WHERE m.device_serial IN ($ph) ORDER BY m.date_performed ASC");$m->execute($sns);foreach($m->fetchAll(PDO::FETCH_ASSOC) as $r)$maint[$r['device_serial']][]=$r;}
function exStorage($d){return !empty($d['storage_capacity'])?$d['storage_capacity'].'GB '.($d['storage_type']??''):'';}
function exDash($v){$v=trim((string)($v??''));return $v===''?'-':$v;}
function exDollar($v){if($v===null||trim((string)$v)==='')return '-';$raw=str_replace([',','$'],'',trim((string)$v));return is_numeric($raw)?'$'.number_format((float)$raw,2):'$'.trim((string)$v);}
function exMfg($d){$m=strtoupper(trim((string)($d['model_name']??'')));if(preg_match('/\bHP\b|HEWLETT[ -]?PACKARD/',$m))return 'HP';if(preg_match('/\bDELL\b/',$m))return 'Dell';if(preg_match('/\bLENOVO\b|THINKPAD|THINKCENTRE|IDEAPAD/',$m))return 'Lenovo';if(preg_match('/\bTOSHIBA\b|DYNABOOK/',$m))return 'Toshiba';if(preg_match('/\bAPPLE\b|MACBOOK|IMAC/',$m))return 'Apple';if(preg_match('/\bASUS\b/',$m))return 'ASUS';if(preg_match('/\bACER\b/',$m))return 'Acer';return exDash($d['manufacturer']??'');}
function exProfit($d){if(($d['selling_price']??null)===null||($d['selling_price']??'')===''||($d['buying_price']??null)===null||($d['buying_price']??'')==='')return '-';return (float)$d['selling_price']-(float)$d['buying_price'];}
function exSp($d){$v=(($d['selling_price']??null)!==null&&($d['selling_price']??'')!=='')?$d['selling_price']:($d['price']??null);return $v===null||$v===''?'-':$v;}
function exMaint($rows){if(!$rows)return 'No maintenance records';$o=[];foreach($rows as $r){$c=[];if($r['old_ram']!==null||$r['new_ram']!==null)$c[]='RAM: '.($r['old_ram']??'?').'GB -> '.($r['new_ram']??'?').'GB';if($r['old_storage']!==null||$r['new_storage']!==null)$c[]='Storage: '.($r['old_storage']??'?').'GB -> '.($r['new_storage']??'?').'GB';if(($r['old_graphics']??'')!==''||($r['new_graphics']??'')!=='')$c[]='Graphics: '.($r['old_graphics']?:'?').' -> '.($r['new_graphics']?:'?');if(!empty($r['notes']))$c[]='Notes: '.$r['notes'];$o[]=date('d M Y H:i',strtotime($r['date_performed'])).' - '.implode('; ',$c).' - '.($r['performed_by_name']??'Unknown');}return implode("\n",$o);}
$headers=$ownerKey==='imans_hustle'?['Asset ID','MFG','Model','Form Factor','CPU','RAM','HDD','Serial','Grade','B.P','S.P','PROFIT','NOTES']:['#','Asset ID','Buying $','Selling $','BP','SP','PROFIT','MFG','Model','CPU','RAM','HDD','Serial #','Grade','Touch Screen','Webcam','Notes','LOCATION'];$headers[]='Status';if($mode==='overview')$headers[]='Maintenance / Changes';if($mode==='sold'){$headers[]='Sold By';$headers[]='Sold At';$headers[]='Actual Selling Price';}
$book=new Spreadsheet();$sheet=$book->getActiveSheet();$title=$mode==='overview'?'Overview':($mode==='instock'?'In Stock':'Sold');$sheet->setTitle(substr($ownerLabel.' '.$title,0,31));$last=Coordinate::stringFromColumnIndex(count($headers));$sheet->setCellValue('A1',$ownerLabel.' - '.$title);$sheet->mergeCells('A1:'.$last.'1');$sheet->getStyle('A1')->getFont()->setBold(true)->setSize(14);$sheet->getStyle('A1')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
$row=2;if($mode==='overview'){$sheet->setCellValue('A2','Date range: '.$df.' to '.$dt);$sheet->mergeCells('A2:'.$last.'2');$row=4;}else$row=3;
foreach($headers as $i=>$h)$sheet->setCellValue(Coordinate::stringFromColumnIndex($i+1).$row,$h);$sheet->getStyle('A'.$row.':'.$last.$row)->getFont()->setBold(true)->getColor()->setARGB('FF111111');$sheet->getStyle('A'.$row.':'.$last.$row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFD7B729');
$r=$row+1;$idx=1;foreach($devices as $d){if($ownerKey==='imans_hustle'){$vals=[$d['asset_id']??'',$d['manufacturer']??'',$d['model_name']??'',$d['form_factor']??'',$d['processor']??'',$d['ram']??'',exStorage($d),$d['serial_number'],$d['grade']??'',$d['buying_price']??'',$d['price']??'',$d['owner_profit']??'',$d['owner_notes']??''];}else{$vals=[$idx++,exDash($d['asset_id']??''),exDollar($d['symetic']??null),exDollar($d['dollar_value']??null),$d['buying_price']??'-',exSp($d),exProfit($d),exMfg($d),exDash($d['model_name']??''),exDash($d['processor']??''),!empty($d['ram'])?$d['ram'].' GB':'-',exStorage($d)?:'-',exDash($d['serial_number']??''),exDash($d['grade']??''),exDash($d['touch']??''),exDash($d['webcam']??''),exDash($d['owner_notes']??''),exDash($d['owner_location']??($d['branch']??''))];}$vals[]=$d['status']??'';if($mode==='overview')$vals[]=exMaint($maint[$d['serial_number']]??[]);if($mode==='sold'){$vals[]=$d['sold_by_name']??'Unknown';$vals[]=$d['sold_at']?date('Y-m-d H:i',strtotime($d['sold_at'])):'';$vals[]=$d['selling_price']??'';}foreach($vals as $i=>$v)$sheet->setCellValue(Coordinate::stringFromColumnIndex($i+1).$r,$v);$r++;}
for($i=1;$i<=count($headers);$i++){$col=Coordinate::stringFromColumnIndex($i);$sheet->getColumnDimension($col)->setAutoSize(true);}if($mode==='overview'){$mc=Coordinate::stringFromColumnIndex(count($headers));$sheet->getStyle($mc.($row+1).':'.$mc.max($row+1,$r-1))->getAlignment()->setWrapText(true);$sheet->getColumnDimension($mc)->setWidth(55);}$sheet->getStyle('A'.$row.':'.$last.max($row,$r-1))->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);$sheet->freezePane('A'.($row+1));
$filename=preg_replace('/[^A-Za-z0-9_-]+/','_',strtolower($ownerLabel.'_'.$mode.'_'.date('Y-m-d'))).'.xlsx';while(ob_get_level()>0)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="'.$filename.'"');header('Cache-Control: max-age=0');$writer=new Xlsx($book);$writer->save('php://output');exit;
