<?php
if (!isset($ownerKey, $ownerLabel, $reportMode)) { die('Inventory report configuration missing.'); }
session_start();
require_once __DIR__ . '/../config/db.php';
require_once __DIR__ . '/auth_check.php';
$role = $_SESSION['role'];
$user_id = (int)$_SESSION['user_id'];
if (!in_array($role, ['super_admin','inventory_admin','manager'])) { die('ACCESS DENIED.'); }
$user_branch='';
if ($role === 'manager') {
    $q=$conn->prepare('SELECT branch FROM users WHERE id=?'); $q->execute([$user_id]);
    $user_branch=(string)($q->fetchColumn() ?: '');
}
$serial=trim($_GET['serial'] ?? ''); $model=trim($_GET['model'] ?? '');
$branch=trim($_GET['branch'] ?? ''); $category=trim($_GET['category'] ?? ''); $status=trim($_GET['status'] ?? '');
$date_from=trim($_GET['date_from'] ?? ''); $date_to=trim($_GET['date_to'] ?? '');
$sql="SELECT d.*, c.category_name, ua.full_name added_by_name, us.full_name sold_by_name
      FROM devices d LEFT JOIN categories c ON c.id=d.category_id
      LEFT JOIN users ua ON ua.id=d.added_by LEFT JOIN users us ON us.id=d.sold_by
      WHERE d.inventory_owner=:owner";
$params=['owner'=>$ownerKey];
if ($reportMode==='instock') $sql.=" AND d.status='In Stock'";
elseif ($reportMode==='sold') $sql.=" AND d.status='Sold'";
elseif ($status!=='') { $sql.=' AND d.status=:status'; $params['status']=$status; }
if ($role==='manager' && $user_branch!=='') { $sql.=' AND d.branch=:manager_branch'; $params['manager_branch']=$user_branch; }
elseif ($branch!=='') { $sql.=' AND d.branch=:branch'; $params['branch']=$branch; }
if ($serial!=='') { $sql.=' AND d.serial_number LIKE :serial'; $params['serial']="%$serial%"; }
if ($model!=='') { $sql.=' AND d.model_name LIKE :model'; $params['model']="%$model%"; }
if ($category!=='') { $sql.=' AND d.category_id=:category'; $params['category']=(int)$category; }
if ($reportMode==='sold' && $date_from!=='') { $sql.=' AND DATE(d.sold_at)>=:date_from'; $params['date_from']=$date_from; }
if ($reportMode==='sold' && $date_to!=='') { $sql.=' AND DATE(d.sold_at)<=:date_to'; $params['date_to']=$date_to; }
$sql .= $reportMode==='sold' ? ' ORDER BY d.sold_at DESC' : ' ORDER BY d.date_added DESC';
$stmt=$conn->prepare($sql); $stmt->execute($params); $devices=$stmt->fetchAll(PDO::FETCH_ASSOC);
$cats=$conn->query('SELECT id, category_name FROM categories ORDER BY category_name')->fetchAll(PDO::FETCH_ASSOC);
$maintenance=[];
if ($reportMode==='sold' && $devices) {
    $sns=array_column($devices,'serial_number'); $ph=implode(',',array_fill(0,count($sns),'?'));
    $m=$conn->prepare("SELECT m.*, u.full_name performed_by_name FROM maintenance m LEFT JOIN users u ON u.id=m.performed_by WHERE m.device_serial IN ($ph) ORDER BY m.date_performed ASC");
    $m->execute($sns);
    foreach($m->fetchAll(PDO::FETCH_ASSOC) as $row) $maintenance[$row['device_serial']][]=$row;
}
function specs($d){$a=[]; foreach(['processor','graphics'] as $k) if(!empty($d[$k])&&$d[$k]!=='None')$a[]=$d[$k]; if(!empty($d['ram']))$a[]=$d['ram'].'GB RAM'; if(!empty($d['storage_capacity']))$a[]=$d['storage_capacity'].'GB '.($d['storage_type']??''); if(!empty($d['touch'])&&$d['touch']!=='N/A')$a[]=$d['touch']; return implode(' | ',$a);}
function maintenanceText($rows){ if(!$rows)return 'No maintenance records'; $out=[]; foreach($rows as $r){$c=[]; if($r['old_ram']!==null||$r['new_ram']!==null)$c[]='RAM: '.($r['old_ram']??'?').'GB → '.($r['new_ram']??'?').'GB'; if($r['old_storage']!==null||$r['new_storage']!==null)$c[]='Storage: '.($r['old_storage']??'?').'GB → '.($r['new_storage']??'?').'GB'; if(($r['old_graphics']??'')!==''||($r['new_graphics']??'')!=='')$c[]='Graphics: '.($r['old_graphics']?:'?').' → '.($r['new_graphics']?:'?'); if(!empty($r['notes']))$c[]='Notes: '.$r['notes']; $out[]=date('d M Y H:i',strtotime($r['date_performed'])).' — '.implode('; ',$c).' — By '.($r['performed_by_name']??'Unknown');} return implode("\n",$out); }
$total=count($devices); $inStock=count(array_filter($devices,fn($d)=>$d['status']==='In Stock')); $sold=count(array_filter($devices,fn($d)=>$d['status']==='Sold')); $revenue=array_sum(array_map(fn($d)=>(float)($d['selling_price']??0),$devices));
$pageTitle=$reportMode==='overview'?'Overview':($reportMode==='instock'?'In Stock':'Sold');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title><?=htmlspecialchars($ownerLabel.' '.$pageTitle)?> | Mombasa Computers</title><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"><style>
:root{--p:#1a4b2a;--bg:#f3f4f6;--b:#e5e7eb;--t:#1f2937;--m:#6b7280}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:var(--bg);color:var(--t)}.main{margin-left:260px;padding:2rem;min-height:100vh}.head,.filters,.card,.tablebox{background:#fff;border:1px solid var(--b);border-radius:14px;box-shadow:0 1px 2px #0000000d}.head{padding:1.4rem 1.6rem;margin-bottom:1rem}.head h1{margin:0 0 .35rem;font-size:1.65rem}.tabs{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:1rem}.tabs a{padding:.55rem .9rem;border-radius:8px;text-decoration:none;color:var(--p);border:1px solid var(--b);font-weight:600}.tabs a.active{background:var(--p);color:white}.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:1rem;margin:1rem 0}.card{padding:1rem}.n{font-size:1.6rem;font-weight:800;color:var(--p)}.l{font-size:.8rem;color:var(--m)}.filters{padding:1rem;margin-bottom:1rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:.75rem}.g{display:flex;flex-direction:column;gap:.3rem}.g label{font-size:.78rem;color:var(--m);font-weight:600}.g input,.g select{padding:.62rem;border:1px solid #d1d5db;border-radius:8px}.actions{display:flex;gap:.5rem;align-items:end}.btn{padding:.62rem .9rem;border:0;border-radius:8px;background:var(--p);color:#fff;text-decoration:none;cursor:pointer}.secondary{background:#6b7280}.tablebox{overflow:hidden}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;min-width:1150px;font-size:.84rem}th,td{padding:.75rem;border-bottom:1px solid #eee;text-align:left;vertical-align:top}th{background:#f9fafb;color:#4b5563;white-space:nowrap}.sn{font-family:monospace;font-weight:700}.badge{display:inline-block;padding:.2rem .5rem;background:#ecfdf5;color:#166534;border-radius:999px;font-size:.74rem;font-weight:700}.maint{white-space:pre-line;min-width:330px;line-height:1.5}.empty{padding:3rem;text-align:center;color:var(--m)}@media(max-width:1200px){.main{margin-left:0;padding:5rem 1rem 1rem}}
</style></head><body><?php include __DIR__.'/sidebar.php'; ?><main class="main"><section class="head"><h1><i class="fas fa-boxes-stacked"></i> <?=htmlspecialchars($ownerLabel)?> — <?=htmlspecialchars($pageTitle)?></h1><div style="color:var(--m)">Devices assigned to <?=htmlspecialchars($ownerLabel)?> only.</div><div class="tabs"><a class="<?=$reportMode==='overview'?'active':''?>" href="overview.php">Overview</a><a class="<?=$reportMode==='instock'?'active':''?>" href="instock.php">In Stock</a><a class="<?=$reportMode==='sold'?'active':''?>" href="sold.php">Sold</a></div></section>
<section class="stats"><div class="card"><div class="n"><?=$total?></div><div class="l"><?= $reportMode==='overview'?'TOTAL DEVICES':'MATCHING DEVICES' ?></div></div><?php if($reportMode==='overview'):?><div class="card"><div class="n"><?=$inStock?></div><div class="l">IN STOCK</div></div><div class="card"><div class="n"><?=$sold?></div><div class="l">SOLD</div></div><?php endif;?><?php if($reportMode==='sold'):?><div class="card"><div class="n">KES <?=number_format($revenue,2)?></div><div class="l">TOTAL SALES VALUE</div></div><?php endif;?></section>
<section class="filters"><form class="grid" method="get"><div class="g"><label>Serial</label><input name="serial" value="<?=htmlspecialchars($serial)?>"></div><div class="g"><label>Model</label><input name="model" value="<?=htmlspecialchars($model)?>"></div><div class="g"><label>Category</label><select name="category"><option value="">All</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>" <?=$category==(string)$c['id']?'selected':''?>><?=htmlspecialchars($c['category_name'])?></option><?php endforeach;?></select></div><?php if($role!=='manager'):?><div class="g"><label>Branch</label><select name="branch"><option value="">All</option><option <?=$branch==='KIMATHI'?'selected':''?>>KIMATHI</option><option <?=$branch==='MOI'?'selected':''?>>MOI</option></select></div><?php endif;?><?php if($reportMode==='overview'):?><div class="g"><label>Status</label><select name="status"><option value="">All</option><?php foreach(['In Stock','Sold','Faulty','Under Repair','Disposed'] as $st):?><option <?=$status===$st?'selected':''?>><?=$st?></option><?php endforeach;?></select></div><?php endif;?><?php if($reportMode==='sold'):?><div class="g"><label>Sold From</label><input type="date" name="date_from" value="<?=htmlspecialchars($date_from)?>"></div><div class="g"><label>Sold To</label><input type="date" name="date_to" value="<?=htmlspecialchars($date_to)?>"></div><?php endif;?><div class="actions"><button class="btn"><i class="fas fa-search"></i> Filter</button><a class="btn secondary" href="<?=$reportMode?>.php">Reset</a></div></form></section>
<section class="tablebox"><div class="scroll"><?php if(!$devices):?><div class="empty">No <?=htmlspecialchars(strtolower($pageTitle))?> devices found for <?=htmlspecialchars($ownerLabel)?>.</div><?php else:?><table><thead><tr><th>#</th><th>Serial</th><th>Category</th><th>Model</th><th>Specifications</th><th>Status</th><th>Branch</th><th>Place</th><th>Added</th><th>Added By</th><?php if($reportMode==='sold'):?><th>Sold By</th><th>Sold At</th><th>Selling Price</th><th>Maintenance / Changes</th><?php endif;?><th>Action</th></tr></thead><tbody><?php foreach($devices as $i=>$d):?><tr><td><?=$i+1?></td><td class="sn"><?=htmlspecialchars($d['serial_number'])?></td><td><?=htmlspecialchars($d['category_name']??'—')?></td><td><strong><?=htmlspecialchars($d['model_name']??'—')?></strong></td><td><?=htmlspecialchars(specs($d))?></td><td><span class="badge"><?=htmlspecialchars($d['status'])?></span></td><td><?=htmlspecialchars($d['branch'])?></td><td><?=htmlspecialchars($d['place']??'—')?></td><td><?=date('d M Y',strtotime($d['date_added']))?></td><td><?=htmlspecialchars($d['added_by_name']??'System')?></td><?php if($reportMode==='sold'):?><td><?=htmlspecialchars($d['sold_by_name']??'Unknown')?></td><td><?=$d['sold_at']?date('d M Y H:i',strtotime($d['sold_at'])):'—'?></td><td><?=$d['selling_price']!==null?'KES '.number_format((float)$d['selling_price'],2):'—'?></td><td class="maint"><?=htmlspecialchars(maintenanceText($maintenance[$d['serial_number']]??[]))?></td><?php endif;?><td><a class="btn" style="padding:.4rem .6rem" href="../devices/view_device.php?sn=<?=urlencode($d['serial_number'])?>"><i class="fas fa-eye"></i> View</a></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></section></main></body></html>
